version: "3"
services:
    web:
        build: .
        ports:
            - "8000:8000"
        stdin_open: true
        tty: true
        command: python manage.py runserver 0.0.0.0:8000
        depends_on:
            - redis
    redis:
        image: redis:5
        ports:
            - "6379:6379"